name: blue_zero

channels:
  - pytorch
  - defaults
#  - conda-forge

dependencies:
  - contextlib2
  - cython
  - ipython
  - matplotlib
  - numpy
  - pip
  - python >=3.8
  - pytorch >=1.6
  - tqdm
  - pip:
      - argparse
      - gym
      - ipdb
      - path.py
      - pygame >=2.0.0
