name: blue_zero

channels:
  - pytorch
  - defaults
#  - conda-forge

dependencies:
  - contextlib2
  - cudatoolkit =11.0 # [linux]
  - cython
  - ipython
  - matplotlib
  - more-itertools
  - numpy >=1.20.0
  - pip
  - python >=3.8
  - pytorch >=1.7
  - pyyaml
  - tqdm
  - pip:
      - gym
      - ipdb
      - pygame >=2.0.0
      - pygame_widgets
      - simple-parsing
      - wurlitzer
