qnet:
  id: 'dueling'
  depth: 5
  kernel_size: 3
  num_feat: 64
  num_hidden: 64
  bias: true
  batchnorm: true
  bn_momentum: 0.01
mode:
  id: 'zero'
  # blank = no normalization of rewards
  reward_norm:
  shape_rewards: false
replay:
  capacity: 1_000_000
  step_diff: 1
training:
  batch_size: 256
  max_epochs: 1_000_000
  eps_decay_time: 500_000
  eps_start: 1.0
  eps_end: 0.1
  gamma: 1.0
  clip_gradients: true
  max_grad: 1.0
  num_burn_in: 1_000
  play_freq: 100
  num_play: 20
  validation_freq: 100
  target_update_mode: soft
  soft_update_rate: 1.0e-5
  hard_update_freq: 10_000
  optimizer:
    name: 'adam'
    lr: 1.0e-5
    eps: 1.0e-2

